### ISSUE TITLE
dptf must not write to /usr/local

### ISSUE THREAD

**Issue by vapier** [intel/dptf#19]
for some reason, main.c hardcodes `/usr/local/var/log/dptf` for the LOG setting.  dptf must not write to anywhere under /usr/local.

**Comment by bbian** [comment]
We can certainly change the default tracing directory to somewhere else, please suggest a one. That said, this feature can only be turned on by developers using an override option, so end users should never see trace messages on production systems.

**Comment by vapier** [comment]
the system creates paths (and does so with bad permissions) regardless of the option being turned on which is why i noticed.  if you want to log somewhere, use /var/log.

**Comment by bbian** [comment]
We will change the default path to /var/log/dptf, but I also noticed that even on existing systems, /usr/local/var is just a symlink to /var, so the logs have been stored in /var/log/dptf all along.

**Comment by vapier** [comment]
that's only the case if you've booted a dev/test image where stateful is already populated.  if you boot a base image in dev mode, dptf will create bad directories with bad perms.  that means release devices today are misbehaving when the system includes dptf.

**Comment by bbian** [comment]
Thanks for the clarification, we will have this fixed in our next release.
