### ISSUE TITLE
Failing to acquire OSC

### ISSUE THREAD

**Issue by coredump** [intel/dptf#22]
Hello. I compiled dptf on a 4.14 kernel linux and when I try to run the daemon my computer automatically shuts down:

```console
Jul 05 16:05:47 cammy DPTF[31225]: ERROR:[<DPTF>]<1530817547107 ms>: DPTF Build Version:  8.4.10401.9999        DPTF Build Date:  Jul  5 2018 18:58:30        Source File:  /home/coredump/dev/dptf_pkg/src/dptf/DPTF/Sources/Policies/PolicyLib/PolicyBase.cpp @ line 1065        Executing Function:  takeControlOfOsc        Message:  Critical Policy: Failed to acquire OSC: Platform supports _OSC but unable to process _OSC request.        Policy:  Critical Policy [0]
Jul 05 16:05:47 cammy DPTF[31225]: INFO:[<ACTION>ActionSystemSet@esif_uf_action_system.c#156]<1530817547110 ms>: SYSTEM_HIBERNATE command received - system hibernate...
Jul 05 16:05:47 cammy DPTF[31225]: INFO:[<ACTION>ActionSystemSet@esif_uf_action_system.c#138]<1530817547120 ms>: SYSTEM_SHUTDOWN command received - temperature = 3182, trip point = 2732
   ```

My suspicion is that I am missing something that is preventing the OSC request, and that makes the daemon go straight to Critical and shutdown/hybernate the machine.

I have a Dell XPS 15 (9560) and it uses DPTF on Windows without issues, so I think it may be something related to kernel config or similar.

If any information could be provided I would be glad. Thanks!

**Comment by bbian** [comment]
It looks like one of the DPTF participant has its critical trip point set to 0 degree (2732 = 273.2K = 0 degree C), and this is the reason that caused the shutdown. 

You can check all the thermal zones under /sys/class/thermal/thermal_zoneX/trip_point_X_[temp|type]. One of these trip point type should be called critical, look for its associated trip_point_X_temp and see if it is set to 0.

**Comment by coredump** [comment]
I checked the files and doesn't seem to have any `critical` type with 0 temp:

```console 
/sys/class/thermal/thermal_zone10/trip_point_0_temp  passive
/sys/class/thermal/thermal_zone10/trip_point_1_temp  passive
/sys/class/thermal/thermal_zone1/trip_point_0_temp  passive
/sys/class/thermal/thermal_zone1/trip_point_1_temp  passive
/sys/class/thermal/thermal_zone2/trip_point_0_temp  passive
/sys/class/thermal/thermal_zone2/trip_point_1_temp  passive
/sys/class/thermal/thermal_zone3/trip_point_0_temp  passive
/sys/class/thermal/thermal_zone3/trip_point_1_temp  passive
/sys/class/thermal/thermal_zone4/trip_point_0_temp  passive
/sys/class/thermal/thermal_zone4/trip_point_1_temp  passive
/sys/class/thermal/thermal_zone5/trip_point_0_temp  passive
/sys/class/thermal/thermal_zone5/trip_point_1_temp  passive
```

THis is what I used:
```zsh
for x in  /sys/class/thermal/thermal_zone*/trip_point*temp; do
  [[ $(cat $x) -eq 0 ]] && echo -n $x && echo " " $(cat ${x%temp}type)
done
```

**Comment by coredump** [comment]
I checked the files and doesn't seem to have any `critical` type with 0 temp:

```console 
/sys/class/thermal/thermal_zone10/trip_point_0_temp  passive
/sys/class/thermal/thermal_zone10/trip_point_1_temp  passive
/sys/class/thermal/thermal_zone1/trip_point_0_temp  passive
/sys/class/thermal/thermal_zone1/trip_point_1_temp  passive
/sys/class/thermal/thermal_zone2/trip_point_0_temp  passive
/sys/class/thermal/thermal_zone2/trip_point_1_temp  passive
/sys/class/thermal/thermal_zone3/trip_point_0_temp  passive
/sys/class/thermal/thermal_zone3/trip_point_1_temp  passive
/sys/class/thermal/thermal_zone4/trip_point_0_temp  passive
/sys/class/thermal/thermal_zone4/trip_point_1_temp  passive
/sys/class/thermal/thermal_zone5/trip_point_0_temp  passive
/sys/class/thermal/thermal_zone5/trip_point_1_temp  passive
```

THis is what I used:
```zsh
for x in  /sys/class/thermal/thermal_zone*/trip_point*temp; do
  [[ $(cat $x) -eq 0 ]] && echo -n $x && echo " " $(cat ${x%temp}type)
done
```

**Comment by bbian** [comment]
The above only lists thermal zone 1 through 5 and then 10, what about 6, 7, 8, 9? Also can you list all the critical trip points defined for each zone even if they are not 0?

**Comment by coredump** [comment]
Those are all the critical ones:

```console
/sys/class/thermal/thermal_zone0/trip_point_2_type critical 105000
/sys/class/thermal/thermal_zone1/trip_point_2_type critical 110000
/sys/class/thermal/thermal_zone2/trip_point_2_type critical 100000
/sys/class/thermal/thermal_zone3/trip_point_2_type critical 75000
/sys/class/thermal/thermal_zone4/trip_point_2_type critical 100000
/sys/class/thermal/thermal_zone5/trip_point_0_type critical 85000
/sys/class/thermal/thermal_zone7/trip_point_0_type critical 115000
/sys/class/thermal/thermal_zone8/trip_point_0_type critical 107000
/sys/class/thermal/thermal_zone9/trip_point_0_type critical 100000
```

**Comment by bbian** [comment]
The trip points do look normal so not sure why DPTF thinks one of them is 0. We may need to find a Dell XPS 15 to debug further. One last thing if you can get us the info of:
1. Dump the contents of /sys/bus/platform/devices/INT3400:00/uuids/available_uuids and current_uuids: This command lists the UUID of the policies supported on your system.
2. One of the thermal zones (normally thermal_zone1) has its type defined as "INT3400 Thermal". For this thermal zone please let us know the setting for the "mode" field (i.e., /sys/class/thermal/thermal_zoneX/mode).

**Comment by coredump** [comment]
```
/sys/bus/platform/devices/INT3400:00/uuids/available_uuids
97C68AE7-15FA-499c-B8C9-5DA81D606E0A
```
```
 /sys/bus/platform/devices/INT3400:00/uuids/current_uuid 
INVALID
```
```
/sys/class/thermal/thermal_zone6/type 
INT3400 Thermal
```

now, zone6 that has the type INT3400 has no `mode` file on it.

I am using `acpi_rev_override=1`  on the kernel command line to avoid a bug with the nvidia card breaking stuff. I will try to remove and reboot and see if there's any change.

**Comment by coredump** [comment]
Well. Booted without the acpi_rev option and still no `mode` file on the INT3400 thermal zone, and DPTF rebooted again when starting the daemon.

**Comment by bbian** [comment]
The available_uuids field normally lists at least 2 UUIDs or more indicating the DPTF policies supported on this system. The "97C68AE7" policy is the Critical Policy monitoring system temperatures and shutting down the system when the temperature is getting to hot. It appears that this is the only policy available in your system (it was configured by OEMs), therefore DPTF will not be very much useful in this case other than monitoring for critical trip points.

Please note that the policies supported in Windows and Linux may differ (again configurable by OEMs). Therefore you may not see the same DPTF performance in Linux and then from the Windows.

**Comment by coredump** [comment]
Oh man. That sucks. I really like how it keeps the computer colder with throttling and etc.

I suppose those policies are not a thing I can download/extract and install around right?

**Comment by bbian** [comment]
Looks like in 4.14 kernel some changes were made to the INT3400 driver to enable "mode" only when Passive 1 Policy is defined. 

https://elixir.bootlin.com/linux/v4.14.53/source/drivers/thermal/int340x_thermal/int3400_thermal.c#L306

This may be the reason DPTF fails to set the mode and therefore issue the subsequent shutdown.

If we remove the condition check then it is possible that we can at least avoid the shutdown. But again, since only critical policy is enabled in this system, even with DPTF running it won't do much besides monitoring for temperatures that may cause system shutdown.

**Comment by bbian** [comment]
Unfortunately no, the only policies that are currently available for Linux is Critical, Passive 1 (Passive Cooling) and Active (the one that controls the fans).

**Comment by coredump** [comment]
You mean they exist, but they are not available on my system (that only has the critical one). Correct?

**Comment by bbian** [comment]
DPTF has many different policies, some of those are for Windows OS only. On Linux only the three mentioned above exist, and they have to be enabled by OEMs in the form of UUIDs as mentioned earlier.

In your case since the OEM only enables Critical Policy UUID, your best bet is to use the open source version of thermal daemon https://github.com/intel/thermal_daemon. This is another IA based thermal management software with basic policies built in (critical, passive and active), and since it does not depend on UUIDs, it should work with the passive trip points defined in the thermal zones.
