### ISSUE TITLE
make errors,installation Step-6

### ISSUE THREAD

**Issue by hy51482** [intel/dptf#26]
I tried installation Step6,but esif_ufd is not build
Could you give me some advice?

make++++ 
++++ ESIF_UF x64 Release Linux GMIN=1
++++ 
gcc -c -Wno-multichar -Werror -fPIE -fPIC -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -fno-strict-overflow -fno-delete-null-pointer-checks -fwrapv -fstack-protector-strong -m64  -I../../ESIF_UF/Sources -I../../ESIF_CM/Sources -I../../ESIF_LIB/Sources -I../../../../Common -DESIF_ATTR_USER  -DESIF_ATTR_DAEMON -DESIF_FEAT_OPT_COMPRESS -DESIF_ATTR_OS_LINUX -DESIF_ATTR_OS_LINUX_HAVE_READLINE  -std=gnu99 -DESIF_FEAT_OPT_ACTION_SYSFS -o ../../ESIF_UF/Sources/lin/esif_uf_sensor_manager_os_lin.o ../../ESIF_UF/Sources/lin/esif_uf_sensor_manager_os_lin.c
In file included from ../../../../Common/esif_ccb_string.h:72:0,
                 from ../../../../Common/esif_ccb_library_lin_user.h:28,
                 from ../../../../Common/esif_ccb_library.h:28,
                 from ../../ESIF_CM/Sources/esif.h:194,
                 from ../../ESIF_UF/Sources/esif_uf.h:22,
                 from ../../ESIF_UF/Sources/lin/esif_uf_sensor_manager_os_lin.c:21:
../../ESIF_UF/Sources/lin/esif_uf_sensor_manager_os_lin.c: In function ‘EsifSensorMgr_RegisterSensors’:
../../../../Common/esif_ccb_string_lin_user.h:83:48: error: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 239 [-Werror=format-truncation=]
 #define esif_ccb_sprintf(siz, str, fmt, ...)   esif_ccb_sprintf_len(siz, snprintf(str, siz, fmt, ##__VA_ARGS__))
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../ESIF_UF/Sources/lin/esif_uf_sensor_manager_os_lin.c:223:2: note: in expansion of macro ‘esif_ccb_sprintf’
  esif_ccb_sprintf(MAX_PATH, fullPath, "%s/%s", gSensorBasePath, devName);
  ^~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from ../../../../Common/esif_ccb.h:90,
                 from ../../ESIF_UF/Sources/lin/esif_uf_sensor_manager_os_lin.c:20:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 22 and 277 bytes into a destination of size 260
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:190: recipe for target '../../ESIF_UF/Sources/lin/esif_uf_sensor_manager_os_lin.o' failed
make: *** [../../ESIF_UF/Sources/lin/esif_uf_sensor_manager_os_lin.o] Error 1

**Comment by bbian** [comment]
Fixed by commit 3844eb88382267f9c1760987bf5df836dfc4d8f2. Please try again. Thank you for pointing this out.
